from typing import List, Dict, Any, Optional
from src.llm.gemini_client import gemini_service
from src.models.retrieved_context import RetrievedContext
from src.llm.prompt_engineer import prompt_engineer
from src.utils.logging import get_logger
from src.exceptions import GeminiGenerationException
from src.models.response import TokenUsage

logger = get_logger(__name__)


class ResponseGenerator:
    """
    Service for generating responses using the LLM with provided context
    """
    def __init__(self):
        self.gemini_service = gemini_service
        self.prompt_engineer = prompt_engineer

    def generate_response(
        self,
        query: str,
        contexts: List[RetrievedContext] = None,
        system_instruction: str = None
    ) -> tuple[str, Optional[TokenUsage]]:
        """
        Generate a response to the query using the LLM
        Returns a tuple of (response_text, token_usage)
        """
        try:
            logger.info(f"Generating response for query: {query[:50]}...")

            # Create the appropriate prompt based on whether context is available
            if contexts and len(contexts) > 0:
                # Use advanced RAG prompt with context-aware formatting
                advanced_prompt = self.prompt_engineer.create_advanced_rag_prompt(
                    query=query,
                    contexts=contexts,
                    system_instruction=system_instruction
                )

                # Try to get response from Gemini
                try:
                    response_text = self.gemini_service.generate_response(
                        prompt=advanced_prompt["user"],
                        context=self._format_context_for_llm(contexts),
                        stream=False
                    )
                except Exception as gemini_error:
                    logger.warning(f"Gemini API error: {str(gemini_error)}. Using mock response.")
                    # Generate a mock response based on the query and context
                    response_text = self._generate_mock_response(query, contexts)
            else:
                # Use fallback prompt when no context is available
                prompt = self.prompt_engineer.create_fallback_prompt(query)
                try:
                    response_text = self.gemini_service.generate_response(
                        prompt=prompt,
                        context=None,
                        stream=False
                    )
                except Exception as gemini_error:
                    logger.warning(f"Gemini API error: {str(gemini_error)}. Using mock response.")
                    # Generate a mock response
                    response_text = f"This is a mock response for your query: '{query}'. In a real implementation with valid API keys, this would be generated by the AI model."

            # Calculate token usage (in a real implementation, this would come from the API response)
            # For now, estimating based on text length
            prompt_tokens = len(query.split()) + (sum(len(ctx.content.split()) for ctx in contexts) if contexts else 0)
            completion_tokens = len(response_text.split()) if response_text else 0
            total_tokens = prompt_tokens + completion_tokens

            token_usage = TokenUsage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=total_tokens
            )

            logger.info("Successfully generated response")
            return response_text, token_usage

        except Exception as e:
            logger.error(f"Error generating response: {str(e)}")
            raise GeminiGenerationException(f"Failed to generate response: {str(e)}")

    def _generate_mock_response(self, query: str, contexts: List[RetrievedContext]) -> str:
        """
        Generate a mock response when the LLM API is not available
        """
        if contexts:
            context_preview = contexts[0].content[:100] if contexts else ""
            return f"Mock response: Based on the context '{context_preview}...', the answer to '{query}' would be provided here. This is a simulated response for development purposes when the real LLM API is not available."
        else:
            return f"Mock response: The answer to '{query}' would be provided here. This is a simulated response for development purposes when the real LLM API is not available."

    def generate_response_streaming(
        self,
        query: str,
        contexts: List[RetrievedContext] = None,
        system_instruction: str = None
    ) -> Any:  # Generator for streaming
        """
        Generate a streaming response to the query using the LLM
        Note: Token usage for streaming responses would need to be accumulated as tokens are generated
        """
        try:
            logger.info(f"Generating streaming response for query: {query[:50]}...")

            # Format context for the LLM
            formatted_context = self._format_context_for_llm(contexts) if contexts else None

            # Create the appropriate prompt
            if contexts and len(contexts) > 0:
                prompt = self.prompt_engineer.create_rag_prompt(
                    query=query,
                    contexts=contexts,
                    system_instruction=system_instruction
                )
            else:
                prompt = self.prompt_engineer.create_fallback_prompt(query)

            # Generate streaming response using the LLM
            stream = self.gemini_service.stream_response(
                prompt=prompt,
                context=formatted_context
            )

            logger.info("Successfully started streaming response")
            return stream

        except Exception as e:
            logger.error(f"Error generating streaming response: {str(e)}")
            raise GeminiGenerationException(f"Failed to generate streaming response: {str(e)}")

    def _format_context_for_llm(
        self,
        contexts: List[RetrievedContext]
    ) -> List[Dict[str, Any]]:
        """
        Format RetrievedContext objects for use with the LLM
        """
        formatted_context = []
        for context in contexts:
            formatted_context.append({
                'content': context.content,
                'url': context.url,
                'section': context.section,
                'relevance_score': context.score
            })
        return formatted_context

    def validate_response_quality(
        self,
        response: str,
        original_query: str,
        contexts: List[RetrievedContext] = None
    ) -> bool:
        """
        Validate the quality of the generated response
        This is a basic implementation - in production, you might want more sophisticated validation
        """
        # Basic checks:
        # 1. Response is not empty
        if not response or len(response.strip()) == 0:
            return False

        # 2. Response has reasonable length
        if len(response) < 10:
            return False

        # 3. If contexts were provided, check if response seems to address the query
        # This is a simple check - in production you might use more advanced NLP techniques
        query_words = set(original_query.lower().split()[:5])  # First 5 words as keywords
        response_words = set(response.lower().split())

        # If there's some overlap in keywords, it's likely relevant
        keyword_overlap = len(query_words.intersection(response_words))

        # Return True if either: no context was provided (hard to validate) or
        # there's some keyword overlap suggesting relevance
        if not contexts or keyword_overlap > 0 or len(response) > 50:  # Long responses likely relevant
            return True

        return False


# Global instance
response_generator = ResponseGenerator()