#!/usr/bin/env python3
"""
ROS 2 Action Message Template for VLA Systems
This demonstrates the structure of ROS 2 action messages used in Chapter 1: VLA Fundamentals
"""

# This would typically be defined in an .action file and generated by actionlib
# For educational purposes, we show how the action structure would work

class TextToAction:
    """
    Action definition for processing text instructions into robot actions
    This is a conceptual representation of what would be generated from a .action file
    """

    class Goal:
        """
        Goal: The text instruction to execute
        """
        def __init__(self):
            self.text_instruction = ""  # The natural language command

    class Result:
        """
        Result: The outcome of the action
        """
        def __init__(self):
            self.success = False      # Whether the action was successful
            self.message = ""         # Descriptive message about the result
            self.executed_commands = []  # List of commands that were executed

    class Feedback:
        """
        Feedback: Progress information during execution
        """
        def __init__(self):
            self.current_step = ""    # Current step being executed
            self.progress = 0.0       # Progress percentage (0.0 to 1.0)
            self.status = ""          # Current status message

# Example usage of the action structure
def example_usage():
    print("ROS 2 Action Message Template Example")
    print("=" * 40)

    # Creating a goal
    goal = TextToAction.Goal()
    goal.text_instruction = "Move the robot to the kitchen and pick up the red cup"

    print(f"Goal instruction: {goal.text_instruction}")

    # Simulating feedback during execution
    feedback = TextToAction.Feedback()
    feedback.current_step = "Parsing natural language instruction"
    feedback.progress = 0.1
    feedback.status = "Processing text with NLP pipeline"

    print(f"Feedback: {feedback.current_step} ({feedback.progress*100}%)")

    # Simulating final result
    result = TextToAction.Result()
    result.success = True
    result.message = "Successfully moved to kitchen and identified red cup"
    result.executed_commands = [
        "navigate_to(kitchen)",
        "detect_object(red_cup)",
        "plan_approach_path()"
    ]

    print(f"Result: {result.message}")
    print(f"Executed commands: {result.executed_commands}")
    print(f"Success: {result.success}")

if __name__ == "__main__":
    example_usage()