from pydantic import BaseModel, Field, validator
from typing import List, Optional
from datetime import datetime
from typing import Dict, Any


class Source(BaseModel):
    """
    Represents a source document used in generating the response
    """
    url: str = Field(
        ...,
        description="Source URL"
    )
    section: str = Field(
        ...,
        description="Section title"
    )
    relevance_score: float = Field(
        ...,
        description="How relevant this source was (0.0-1.0)",
        ge=0.0,
        le=1.0
    )


class TokenUsage(BaseModel):
    """
    Represents token usage information
    """
    prompt_tokens: int = Field(
        ...,
        description="Number of tokens in the prompt",
        ge=0
    )
    completion_tokens: int = Field(
        ...,
        description="Number of tokens in the completion",
        ge=0
    )
    total_tokens: int = Field(
        ...,
        description="Total number of tokens used",
        ge=0
    )


class ChatResponse(BaseModel):
    """
    Represents the final output generated by the Gemini agent
    """
    id: str = Field(
        ...,
        description="Unique response identifier"
    )
    answer: str = Field(
        ...,
        description="The generated answer to the user's query"
    )
    sources: List[Source] = Field(
        ...,
        description="List of source documents used"
    )
    created_at: str = Field(
        ...,
        description="ISO 8601 timestamp"
    )
    model: str = Field(
        ...,
        description="Name of the model used"
    )
    usage: Optional[TokenUsage] = Field(
        None,
        description="Token usage information"
    )

    @validator('answer')
    def validate_answer(cls, v):
        """
        Validate that answer is not empty
        """
        if not v or not v.strip():
            raise ValueError('Answer must be non-empty')
        return v

    @validator('created_at')
    def validate_timestamp(cls, v):
        """
        Validate that timestamp is in ISO 8601 format
        """
        try:
            datetime.fromisoformat(v.replace('Z', '+00:00'))
        except ValueError:
            raise ValueError('created_at must be valid ISO 8601 format')
        return v

    @validator('sources')
    def validate_sources(cls, v):
        """
        Validate that sources array contains valid source objects
        """
        if not v:
            raise ValueError('Sources array must not be empty')
        return v